<script setup>
import{computed,onMounted,ref}from"vue";import{Activity,AlertTriangle,ArrowUpRight,CheckCircle2,CircleDot,ExternalLink,FlaskConical,LogOut,RefreshCw,Satellite,ScanLine,Sparkles,Telescope,X}from"lucide-vue-next";import{connectWallet,contractAddress,explorerUrl,formatError,readContract,writeContract}from"./services/genlayer";
const K="fieldsignal:wallet-connected",ready=ref(false),wallet=ref(null),client=ref(null),busy=ref(false),error=ref(""),loading=ref(false),mode=ref("field"),selected=ref("SEN-001"),modal=ref(null),tx=ref({open:false,stage:"",title:"",hash:"",error:""});
const overview=ref({}),stations=ref([]),sensors=ref([]),signals=ref([]),incidents=ref([]),inspections=ref([]);
const form=ref({value:"42 µg/m³",observed_at:new Date().toISOString(),context:"A sustained anomaly appeared across consecutive intervals with supporting context from nearby activity and neighboring sensor behavior.",evidence_url:"https://github.com/AbstrusImad/fieldsignal"});
const inspection=ref({plan:"Verify physical condition and calibration, collect a co-located reference sample, document nearby activity, and publish time-aligned evidence.",findings:"Field inspection confirmed the device condition and compared its reading against a traceable reference instrument with timestamped context.",evidence_url:"https://github.com/AbstrusImad/fieldsignal"});
const current=computed(()=>sensors.value.find(x=>x.id===selected.value)||sensors.value[0]),station=id=>stations.value.find(x=>x.id===id),short=(v="")=>`${v.slice(0,6)}…${v.slice(-4)}`;
async function restore(){if(localStorage.getItem(K)==="true")try{const s=await connectWallet({silent:true});if(s)enter(s)}catch{localStorage.removeItem(K)}ready.value=true}async function connect(){busy.value=true;try{const s=await connectWallet();if(!s)throw Error("Wallet not connected");localStorage.setItem(K,"true");enter(s)}catch(e){error.value=formatError(e)}finally{busy.value=false}}function enter(s){wallet.value=s.address;client.value=s.client;load()}function logout(){localStorage.removeItem(K);wallet.value=null}
async function load(){loading.value=true;try{const v=[];for(const n of["get_overview","get_stations","get_sensors","get_signals","get_incidents","get_inspections"])v.push(await readContract(n));[overview.value,stations.value,sensors.value,signals.value,incidents.value,inspections.value]=v}catch(e){error.value=formatError(e)}finally{loading.value=false}}
async function transact(title,functionName,args){tx.value={open:true,stage:"signature",title,hash:"",error:""};try{const r=await writeContract({client:client.value,functionName,args,onStage:(stage,hash)=>{tx.value.stage=stage;if(hash)tx.value.hash=hash}});tx.value.hash=r.hash;await load()}catch(e){tx.value.stage="failed";tx.value.error=formatError(e)}}
const submit=()=>transact("Transmit field signal","submit_signal",[current.value.id,form.value.value,form.value.observed_at,form.value.context,form.value.evidence_url]);const resolve=id=>transact("Correlate environmental signal","resolve_signal",[id]);const assign=i=>transact("Dispatch field inspection","assign_inspection",[i.id,inspection.value.plan]);const submitInspection=i=>transact("Publish inspection findings","submit_inspection",[i.id,inspection.value.findings,inspection.value.evidence_url]);const review=id=>transact("Resolve field inspection","resolve_inspection",[id]);onMounted(restore);
</script>
<template><div v-if="!ready" class="boot">CALIBRATING</div>
<main v-else-if="!wallet" class="calibration-gate">
 <div class="scope"><i v-for="n in 48" :key="n" :style="{transform:`rotate(${n*7.5}deg)`}"></i><div class="sweep"></div><div class="pulse p1"></div><div class="pulse p2"></div><section><small>LIVE ENVIRONMENTAL INTEGRITY</small><h1>FIELD<br>SIGNAL</h1><p>Correlate the world before declaring an incident.</p></section></div>
 <aside><span>STUDIONET / 06 STATIONS</span><div><b>08</b><small>SENSORS ONLINE</small></div><button :disabled="busy" @click="connect"><CircleDot/><span>{{busy?"CALIBRATING":"CALIBRATE WALLET"}}</span><ArrowUpRight/></button><p>{{error}}</p></aside>
</main>
<div v-else class="observatory">
 <header class="orbit-controls"><b>FS</b><button v-for="m in ['field','signals','response']" :key="m" :class="{active:mode===m}" @click="mode=m">{{m}}</button><a :href="`${explorerUrl}/address/${contractAddress}`" target="_blank"><ExternalLink/></a><button :class="{spin:loading}" @click="load"><RefreshCw/></button><button @click="logout"><LogOut/></button></header>
 <main v-if="mode==='field'" class="field-view">
  <div class="scope live-scope"><i v-for="n in 48" :key="n" :style="{transform:`rotate(${n*7.5}deg)`}"></i><div class="sweep"></div><div class="sensor-orbit"><button v-for="(s,i) in sensors" :key="s.id" :class="{active:selected===s.id,quarantine:s.status!=='ACTIVE'}" :style="{transform:`rotate(${i*45}deg) translateY(-220px) rotate(${-i*45}deg)`}" @click="selected=s.id">{{s.id.slice(-2)}}</button></div><section v-if="current"><small>{{current.id}} / {{current.status}}</small><h2>{{current.metric}}</h2><b>{{current.baseline}} {{current.unit}}</b><p>{{station(current.station_id)?.name}}</p><button @click="modal='signal'"><Activity/> Transmit reading</button></section></div>
  <div class="telemetry"><span><b>{{overview.stations}}</b> stations</span><span><b>{{overview.active_sensors}}</b> trusted sensors</span><span><b>{{overview.open_incidents}}</b> open incidents</span><span><b>{{overview.pending_signals}}</b> awaiting consensus</span></div>
 </main>
 <main v-else-if="mode==='signals'" class="wave-view"><header><small>CORRELATION QUEUE</small><h1>Signals in<br>question.</h1></header><section><article v-for="s in signals" :key="s.id"><span>{{s.id}}</span><div><small>{{s.sensor_id}} / {{station(sensors.find(x=>x.id===s.sensor_id)?.station_id)?.name}}</small><h2>{{s.value}}</h2><p>{{s.context}}</p></div><div class="wave"><i v-for="n in 16" :key="n" :style="{height:`${8+((n*Number(s.severity||17))%52)}px`}"></i></div><b>{{s.verdict||s.status}}</b><button v-if="s.status==='PENDING'" @click="resolve(s.id)"><Sparkles/> Correlate</button></article></section></main>
 <main v-else class="response-view"><header><small>FIELD RESPONSE ARRAY</small><h1>Incidents / inspections</h1></header><section><article v-for="i in incidents" :key="i.id"><div class="severity"><b>{{i.severity}}</b><span>SEVERITY</span></div><div><small>{{i.id}} / {{i.station_id}}</small><h2>{{i.title}}</h2><p>{{i.response}}</p></div><b>{{i.status}}</b><button v-if="!i.inspection_id" @click="assign(i)"><Telescope/> Dispatch</button></article><article v-for="i in inspections" :key="i.id" class="inspection"><FlaskConical/><div><small>{{i.id}} / {{i.incident_id}}</small><h2>{{i.verdict||i.status}}</h2><p>{{i.findings||i.plan}}</p></div><button v-if="i.status==='ASSIGNED'" @click="modal={type:'inspection',item:i}">Submit findings</button><button v-if="i.status==='PENDING_REVIEW'" @click="review(i.id)"><Sparkles/> Review</button></article></section></main>
 <div v-if="modal" class="probe-modal" @click.self="modal=null"><section><button @click="modal=null"><X/></button><small>FIELD INPUT / PUBLIC RECORD</small><h2>{{modal==='signal'?'Transmit reading':'Inspection findings'}}</h2><template v-if="modal==='signal'"><label>Observed value<input v-model="form.value"></label><label>Timestamp<input v-model="form.observed_at"></label><label>Environmental context<textarea v-model="form.context"></textarea></label><label>Evidence URL<input v-model="form.evidence_url"></label><button class="send" @click="submit">TRANSMIT <Satellite/></button></template><template v-else><label>Findings<textarea v-model="inspection.findings"></textarea></label><label>Evidence URL<input v-model="inspection.evidence_url"></label><button class="send" @click="submitInspection(modal.item)">PUBLISH <Satellite/></button></template></section></div>
 <aside v-if="tx.open" class="signal-tx"><button @click="tx.open=false"><X/></button><ScanLine/><small>GENLAYER CORRELATION</small><h3>{{tx.title}}</h3><div class="mini-wave" :class="tx.stage"><i v-for="n in 12" :key="n"></i></div><p>{{tx.stage==='signature'?'Confirm transmission in wallet.':tx.stage==='consensus'?'Validators are correlating calibration, context, and evidence.':tx.stage==='accepted'?'Observation state updated.':tx.error}}</p></aside>
</div></template>
